#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check

# api_get_me:
#     path: api/get/me
#     methods: ['GET']
#     defaults:
#         _controller: App\Controller\GetSelfUserController::getMyself
#         _api_resource_class: App\Entity\User